### ISSUE TITLE
No contrib on 10 dec 2018

### ISSUE THREAD

**Issue by dgr8akki** [Chiranjivee/data-structures-and-algorithms-practice-cj#69]

**Comment by mukeshsingal** [comment]
Tumhari aankho me motiya ho gya hai 😝

**Comment by dgr8akki** [comment]
@mukeshsingal Are oh ****** vale chacha... 
Tum bina jaane kahe comment krte ho? 😆 
@Chiranjivee or tum private views bnd krke rakhe ho be 🤣
